### ISSUE TITLE
unify UI text

### ISSUE THREAD

**Issue by ququzone** [puncsky/extension-beancount-wallet#104]
- View on IoTexscan

<img width="325" alt="截屏2021-01-27 下午2 19 03" src="https://user-images.githubusercontent.com/455827/105951195-a098b000-60aa-11eb-8948-26383c52b690.png">
<img width="278" alt="截屏2021-01-27 下午2 18 46" src="https://user-images.githubusercontent.com/455827/105951216-a7bfbe00-60aa-11eb-852c-424fcc9c9a99.png">

**Comment by puncsky** [comment]
fixed in https://github.com/puncsky/extension-beancount-wallet/commits/master
