### ISSUE TITLE
member portal does not connect to wallet

### ISSUE THREAD

**Issue by simonerom** [puncsky/extension-beancount-wallet#105]
With Beancount Wallet plugin open and unlocked, member.iotex.io/my-votes cannot connect to the wallet:

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/11096047/106490875-8ef24680-64b6-11eb-8360-6894e0bcb143.png">

**Comment by puncsky** [comment]
iotexproject/web-native-staking-v2@635f500
